microcontroller:
  idmcu: 1 # id of mcu 
  namespace: "ieee" # namespace
  generate_library_Path: "Arduino/libraries"  # path for generate library
  connection:
    type: "UART"   # ["UART","UDP"] support 2 mode 1.Serial UART 2.Wifi UDP (Only arduino and esp32)
    serial_port: "/dev/ttyUSB0"  # for Serial UART example "/dev/ttyUSB0"
    baudrate: 115200  # for UART
    ip_address_mcu: ""  # for UDP example "192.168.1.xx"
    udp_port_mcu: 8888  # for UDP


ros: # setup ros is reference from microcontroller example publisher is mean microcontroller publish to ros network
  publisher:  [[1,"ultrasonic_msg","std_msgs/Int16.msg"],[2,"yaw_msg","std_msgs/Float32.msg"]]
  subscriber: [[3,"control_msg", "geometry_msgs/Twist.msg"]]
  srv_client: [                           ]
  srv_server: [                           ]
  action_client: [                        ]
  action_server: [                        ]

